### ISSUE TITLE
Gridcoin wallet crashes with assertion failure

### ISSUE THREAD

**Issue by pls2000** [gridcoin-community/Gridcoin-Research#1200]
![gridcoin](https://user-images.githubusercontent.com/29391039/42308316-09aee7ac-7fea-11e8-94f2-9219483701ad.png)

----------
Assertion failed!
Program: D:\Program Files\GridcoinResearch\gridcoinresearch.exe
File: Kernel.cpp, line 736
Expression: pindex->ppref || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)
----------

This is running in Windows 10 x64 version 1709. The failure appears to happen after the database is read at startup, but before the real user interface is displayed. The failure is consistent.

==================Fron debug.log
07/05/18 07:24:13 ***************************************** GRIDCOIN RESEARCH ***************************************************
07/05/18 07:24:13 Gridcoin version v3.7.13.0-g9c821ca73 (2018-06-02 10:54:53 +0200)
07/05/18 07:24:13 Using OpenSSL version OpenSSL 1.0.1k 8 Jan 2015
07/05/18 07:24:13 Default data directory C:\Users\pls\AppData\Roaming\GridcoinResearch
07/05/18 07:24:13 Used data directory C:\Users\pls\AppData\Roaming\GridcoinResearch
07/05/18 07:24:13 dbenv.open LogDir=C:\Users\pls\AppData\Roaming\GridcoinResearch\database ErrorFile=C:\Users\pls\AppData\Roaming\GridcoinResearch\db.log
07/05/18 07:24:13 Loading block index...
07/05/18 07:24:13 Mode=Prod
07/05/18 07:24:13 Opening LevelDB in C:\Users\pls\AppData\Roaming\GridcoinResearch\txleveldb
07/05/18 07:24:13 Transaction index version is 180015
07/05/18 07:24:13 Opened LevelDB successfully
07/05/18 07:24:13 Loading DiskIndex 0
07/05/18 07:25:13 Time to memorize diskindex containing 1301615 blocks :           60102ms

**Comment by barton2526** [comment]
I believe the issue here is rather simple.  You are running the program from
`D:\Program Files\GridcoinResearch\gridcoinresearch.exe`

yet the data directory used by the wallet is listed in the debug log as
`C:\Users\pls\AppData\Roaming\GridcoinResearch`

If you are using a non-standard data directory you need to launch the wallet with the `-datadir` parameter and define the folder it should use.

**Comment by pls2000** [comment]
C:\Users\pls\AppData\Roaming\GridcoinResearch is the default location for the data directory and has been for as long as I've been running Gridcoin.

**Comment by barton2526** [comment]
My point was that the .exe is running on a different drive (D).  That could be the cause of the issue.

**Comment by pls2000** [comment]
Well, I can say that all previous versions I've run in the last 13 months worked fine in the configuration. 
Regardless, I'm hoping someone familiar with the source can look at this and comment. Making a wild ass guess, I'm thinking my database is corrupted. But reloading the database is a large enough effort that I'd rather not do a full reload on speculation.

**Comment by barton2526** [comment]
The alternative is that your blockchain is corrupt.  Did you experience a sudden shutdown while the wallet was running?  Perhaps a power failure or an unexpected system shutdown?  If so, you'll likely need to repair your chain data by downloading a snapshot and syncing back up.

**Comment by iFoggz** [comment]
Blockchain is corrupt. Cant verify genesis block as a corrupt database wud
have undefined output. Likely windows shutdown before wallet did or power
outage. Force shutdowns will not allow database to be close properly

**Comment by pls2000** [comment]
Ok, given that advice, last night I dumped my database, loaded the snapshot from gridcoin,us, and let the wallet run. It went past the point of crash, displayed the user interface, and started syncing. 

Turned out the snapshot I downloaded was from back in March, so I let it sync and went to bed.

This morning, I find that the wallet says "out of sync" and "Staking". I didn't think it was possible for both to happen at once.  Based on transactions, my wallet is reasonably up to day and I have many connections to other nodes. So why still out of sync? Is there another fork happening?

**Comment by barton2526** [comment]
Try restarting the wallet software and see if that fixes the "out of sync" message.

**Comment by pls2000** [comment]
I've restarted twice today. Each time the wallet eventually comes back to Staking and Out of Sync. I currently have 78 connections.

**Comment by iFoggz** [comment]
Try another restart

**Comment by pls2000** [comment]
Restart did not help. But I would not believe what I saw if I hadn't seen it twice now.

I restarted the wallet. It made connections and within a few minutes had updated to exactly 2 blocks less than the current block number from the block explorer. Exactly as described 2 messages back. Now, two hours later, the wallet still shows exactly the same block number. I have not unlocked the wallet.

It seems to get stuck on block n-2.

I'll leave the wallet running overnight and see what it says tomorrow.

**Comment by pls2000** [comment]
Yep, 14 hours later the wallet's block count has not advanced at all.

**Comment by jamescowens** [comment]
Please post your debug.log for review.

**Comment by pls2000** [comment]
Well. This is frustrating.

I deleted the debug.log file and started the wallet. It synced up without problem. So I added back the autounlock line to the the control file and did it again. This time it also synced up and started staking.

All I can say is if the hang happens again I will post the log. I'll leave this open for a bit.

**Comment by pls2000** [comment]
Everything has been running file for several days now. Granted, I'm very suspicious of problems that mysteriously vanish because they tend to mysteriously come back. But I think I should close this until it happens again.

**Comment by pls2000** [comment]
The problem has returned with exactly the same message. Since downloading the database snapshot did not fix the problem last time I haven't tried that this time. 

What do I do now?

**Comment by iFoggz** [comment]
this is really odd because most common to this is a database being corrupted. based on fact your on windows makes me think the wallet didnt get to finish shutting down, maybe a windows update forced a system restart but didnt allow it to shutdown all the way. when u used the snap shot u deleted the txleveldb folder as well as blk0001.dat?

**Comment by pls2000** [comment]
Yes, I did. When I downloaded the official snapshot last time it appeared to be from about April. After installing the snapshot, the wallet trundled for several hours and came to the same error. I actually then downloaded and installed the snapshot again, getting the same result. Each restart, without installing the snapshot, gave the same crash, until one time it didn't. I have no idea what was different.

It's possible that if I wait a week or so and restart the client that everything will work.

Abrupt shutdown happen, and something like the wallet needs to be as close to immune to them as possible.

**Comment by iFoggz** [comment]
that is weird i was not aware that the wallet can come to that error at any point except when wallet is loaded.

**Comment by pls2000** [comment]
I found some extra time and downloaded the official snapshot and installed it again. The wallet started without the error. But now 10 hours later that wallet is saying "out of sync" at block 1320903 at 13:10 MST, and saying "Staking". Again, I didn't know it was possible for both of these to be true.

The wallet can't be very far out of sync. It shows a transaction from 2018-07-31 at 05:.02 MST.

**Comment by iFoggz** [comment]
sometimes a restart of wallet after gets stuck syncing can rectify that and resume syncing

**Comment by pls2000** [comment]
I've restarted many times. When I check on the wallet, 9 out of 10 times it is staking & out of sync. But it seems to go back and forth. I've had the wallet start up and sync + stake, but I come back some hours later and it is staking & out of sync. Rarely, I leave it running staking & out of sync, and come back a few hours later and it is staking & synced.

As I said, I don't see how staking & out of sync is possible. Something is wrong there.

**Comment by iFoggz** [comment]
if your wallet is not encrypted it will try to stake regardless thou it will not succeed. thou its completely rare that a wallet in not encrypted on production network as a simple breach of computer and copy of the wallet.dat would make your funds easily stolen

**Comment by pls2000** [comment]
My wallet is encrypted, but I have the auto-unlock line in the config file.

**Comment by pls2000** [comment]
I updated to 3.7.15.0 earlier today. It has not made a difference. 

As a specific example, I restarted the wallet when the last block (from block explorer) was 1326630. The wallet quickly download blocks, synced, and started staking. I let it run.

Now, 45 minutes or so later, the current block is 1326657. My wallet shows the current block as 1326632, and shows out of sync and staking. So even if it syncs up on start, it won't stay synced.

**Comment by iFoggz** [comment]
You are a researcher solo or for pool? Can you go getmininginfo in rpc and
see if you have rejected stakes at all

**Comment by pls2000** [comment]
I am pool mining.

It looks like there is an error, but I don't know how to interpret the error code:
"errors": "EXCEPTION: St13runtime_error \nCDB() : can't open database file wallet.dat, error -30974 \nD:\\Program Files\\GridcoinResearch\\gridcoinresearch.exe in ProcessMessages()\n",


22:46:55 |   | {
"blocks": 1327360,
"stakeweight": {"minimum": 0,"maximum": 2255,"combined": 147890,"valuesum": 1849.731623339999,"legacy": 1849.73162334},
"netstakeweight": 2112964291.859195,
"netstakingGRCvalue": 26412053.64823994,
"staking": true,
"mining-error": "",
"time-to-stake_days": 23.95277777777778,
"expectedtime": 2069520,
"mining-version": 9,
"mining-created": 0,
"mining-accepted": 0,
"mining-kernels-found": 0,
"InterestPending": 16.57303368455986,
"kernel-diff-best": 0.04618923020056551,
"kernel-diff-sum": 0.0001494832105196623,
"difficulty": {"proof-of-stake": 2.404938959673993,"last-search-interval": 1533620560},
"errors": "EXCEPTION: St13runtime_error \nCDB() : can't open database file wallet.dat, error -30974 \nD:\\Program Files\\GridcoinResearch\\gridcoinresearch.exe in ProcessMessages()\n",
"pooledtx": 446,
"stakeinterest": 0.015,
"testnet": false,
"PopularNeuralHash": "",
"NeuralPopularity": -1,
"MyNeuralHash": "d41d8cd98f00b204e9800998ecf8427e",
"CPID": "INVESTOR",
"RSAWeight": 0,
"Magnitude Unit": 0.225,
"BoincRewardPending": 0,
"MiningInfo 1": "",
"MiningInfo 2": "Poll: Adding_a_very_important_Discord_emoji_and_puppies.",
"MiningInfo 5": "",
"MiningInfo 6": "",
"MiningInfo 7": "",
"MiningInfo 8": ""
}
-- | -- | --

**Comment by tomasbrod** [comment]
`can't open database file wallet.dat`, that means the file, wallet.dat, is corrupted

**Comment by G-UK** [comment]
Try launching the client with the -salvagewallet flag set, this may be able to recover the wallet.

**Comment by pls2000** [comment]
This seems to have worked. The wallet has been running fine for 4 days now.

I had done repairwallet from the debug console. How is -salvagewallet different?

**Comment by iFoggz** [comment]
salvage wallet basically rewrites your privatekeys  and rescans to find all transactions in a sense a clean slate

**Comment by iFoggz** [comment]
it preforms a -rescan after the rewrite of keys

**Comment by jamescowens** [comment]
Any further occurrences on this?

**Comment by jamescowens** [comment]
Closing. The corruption on Windows update due to fast reboot (with Windows not waiting for programs to end) has been fixed by 4.0.2.0 (Camilla).

If this recurs we can reopen.

**Comment by JStateson** [comment]
I am debugging the same problem.  Assertion failed at line 731 version 4.0.4 same code expression.  I tried that -salvagewallet and still have problems..  This first showed up Wednesday morning after the Tuesday Microsoft update (Aug/12/2019 usa).  System had rebooted during night but seems 4.0.4 did not shut down gracefully.  It has been a while since this has happened and I do not remember the procedure for resyncing from the snapshot.  Is there a walkthrough for this?
Thanks !

[EDIT] Ok, found this https://gridcoin.us/Guides/acquire-grc.htm
taking a while to download the snapshot.  Will rename C:\Users\josep\AppData\Roaming\GridcoinResearch
into a backup directory.  Make a new C:\Users\josep\AppData\Roaming\GridcoinResearch
and put the wallet.dat and that config file plus the unzipped snapshot there
Then restart the research program??

[EDIT - 2]  The above worked.  Something in that data file got corrupted and the new download from the snapshot worked.

**Comment by MacGeyer** [comment]
Same problem here after a VM hard reset

**Comment by strongsilenttype** [comment]
however annoying, it seems like taking a new snapshot fixes the issue. v4.0.5.0
