### ISSUE TITLE
Download option in GUI downloads a 404 page and crashes

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#148]
v3.5.8.2-g-research (Arch Linux, installed from aur)
Clicked rebuild->download, something was downloaded to .GridcoinResearch/upgrade/snapshot.zip
but it was not zip but a 404 html page. Update of course failed then and crashed the client.
I don't use proxy.

**Comment by datenklause** [comment]
same on ubuntu, v3.5.8.2-g-research self compiled

**Comment by tomasbrod** [comment]
v3.5.8.3-g-research Issue still exists

**Comment by Lenni** [comment]
I guess this issue is fixed now. @tomasbrod can you close the thread?

**Comment by tomasbrod** [comment]
I will close this once I test that it really works on both Linux and win.
Edit: this issue still persists

**Comment by truboxl** [comment]
Same on Fedora 26
I try capturing the app telling curl to download snapshot.zip from whatever URL using Wireshark
and it looks like its accessing

http://download.gridcoin.us/download/signed/snapshot.zip

instead of the correct URL

http://download.gridcoin.us/download/downloadstake/signed/snapshot.zip

Please fix? Also make it the debug option more visible...

**Comment by denravonska** [comment]
Cool, we'll include it in this release if it works.

**Comment by iFoggz** [comment]
this is an easy fix. thanks for the heads up ravon :)

**Comment by denravonska** [comment]
Fixed by #727.
