### ISSUE TITLE
Diagnostics error

### ISSUE THREAD

**Issue by 47an** [gridcoin-community/Gridcoin-Research#170]
Getting an socket error to diagnostics in popup

![jit error](https://cloud.githubusercontent.com/assets/16613978/21569693/852c5ce4-cebf-11e6-96c3-19202552052a.png)

It say that can´t connect and request was denied.
Message in Swedish:

Information om att aktivera JIT-felsökning i stället för den 
här dialogrutan finns i slutet av det här meddelandet.

************** Undantagstext **************
System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 107.161.152.223:5000
   vid System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   vid System.Net.WebClient.DownloadString(Uri address)
   vid System.Net.WebClient.DownloadString(String address)
   vid BoincStake.modGRC.GetUserRac(String sCPID, String& errors, String& sTable, Double& dProjectByteLength)
   vid BoincStake.modGRC.GetTotalCPIDRAC(String sCPID, String& sError)
   vid BoincStake.frmDiagnostics.VerifyCPIDIsValid(Int32 iRow)
   vid BoincStake.frmDiagnostics.btnRunDiagnostics_Click(Object sender, EventArgs e)
   vid System.Windows.Forms.Control.OnClick(EventArgs e)
   vid System.Windows.Forms.Button.OnClick(EventArgs e)
   vid System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   vid System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   vid System.Windows.Forms.Control.WndProc(Message& m)
   vid System.Windows.Forms.ButtonBase.WndProc(Message& m)
   vid System.Windows.Forms.Button.WndProc(Message& m)
   vid System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   vid System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   vid System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Inlästa sammansättningar **************
mscorlib
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BoincStake
    Sammansättningsversion: 1.20.8.79
    Win32-version: 1.20.8.79
    CodeBase: file:///C:/Program%20Files%20(x86)/GridcoinResearch/BoincStake.DLL
----------------------------------------
Microsoft.VisualBasic
    Sammansättningsversion: 10.0.0.0
    Win32-version: 14.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1081.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1084.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
mscorlib.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.VisualBasic.resources
    Sammansättningsversion: 10.0.0.0
    Win32-version: 14.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic.resources/v4.0_10.0.0.0_sv_b03f5f7f11d50a3a/Microsoft.VisualBasic.resources.dll
----------------------------------------
GRCSec
    Sammansättningsversion: 1.0.0.3
    Win32-version: 1.0.0.3
    CodeBase: file:///C:/Program%20Files%20(x86)/GridcoinResearch/GRCSec.DLL
----------------------------------------
System.Data
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Configuration
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Transactions
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Data.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/System.Data.resources.dll
----------------------------------------
System.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Sammansättningsversion: 0.86.0.518
    Win32-version: 0.86.0.518
    CodeBase: file:///C:/Program%20Files%20(x86)/GridcoinResearch/ICSharpCode.SharpZipLib.DLL
----------------------------------------
System.Web
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Windows.Forms.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT-felsökning **************
För att aktivera JIT-felsökning (just-in-time ) måste .config-filen för det här
tillämpningsprogrammet eller datorn (machine.config) ha 
jitDebugging-värdet angivet i avsnittet system.windows.forms.
Tillämpningsprogrammet måste också vara kompilerat med felsökning
aktiverat.

Till exempel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

När JIT-felsökning är aktiverad kommer alla undantag som inte hanteras
att skickas till JIT-felsökaren som är registrerad på datorn
snarare än att hanteras av den här dialogrutan.

**Comment by jitsuCM** [comment]
Getting the exact same error.
Also it's probably the cause of my CPID going INVESTOR mode.

Exception is thrown at verifying if the CPID is valid part of the diagnostics.

**Comment by gridcoin** [comment]
Fixed in new version.

**Comment by Erkan-Yilmaz** [comment]
2 users still experience this in 3.5.8.4:
- G: same error again and also lost connetion to irc after that
- L: confirms the message in pic above
